version: '3.8'

services:
  cargo_app:
    container_name: cargo_app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: >
      sh -c "
        echo 'Launching tests...' &&
        pytest -vv
      "
    expose:
      - 8000
    ports:
      - "8000:8000"
